### ISSUE TITLE
CMS DQP : PPRL linked Cohort visits and domain count comparison 

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#115]

**Comment by chrisroederucdenver** [comment]
I went to office hours to learn more about the different projects involved and how to access them all. I first thought we'd need to export from the CMS D&R, but see that all of OMOP, restricted to linked patients, is in the same place as the mapping files. Would we now just need a project that access to the first three below as exports?

- /UNITE/Data Ingestion & OMOP Mapping/LDS Union/unioned_\<OMOP table\>
- /UNITE/[PPRL] Centers for Medicare & Medicaid Services (CMS) Release/datasets/Medicaid Datasets - OMOP format/cms_person_id_to_n3c_person_id
- /UNITE/[PPRL] Centers for Medicare & Medicaid Services (CMS) Release/datasets/Medicare Datasets - OMOP format/cms_person_id_to_n3_person_id

When first looking, I thought we'd use these, but all of OMOP Is in the same places as the mapping files above.
- /UNITE/[PPRL] CMS Data & Repository/pipeline/staging/\<OMOP table\>
- /UNITE/[PPRL] CMS Data & Repository/medicaid/pipeline/staging/\<OMOP table\>

**Comment by Leskena2** [comment]
Chris - is this one yours? Per my notes from Tuesday, I think we said this is done. Can this ticket be closed now?

**Comment by chrisroederucdenver** [comment]
Not mine, sorry. I added the comments b/c I was curious, but was shooed away to finish SN.
I think it's Bryan's task and I don't think he's on this part of github.... @bryan @brian @laraway @blaraway don't work.
@Leskena2 @stephanieshong

**Comment by Leskena2** [comment]
@stephanieshong  my notes from Tuesday say we can close this ticket. Is that correct? I closed it in JIRA but let me know if you want me to reopen it.

**Comment by stephanieshong** [comment]
Here is the counts of domains - https://unite.nih.gov/workspace/slate/app/n3c-cms-pprl-linked-sites-dashboard

**Comment by stephanieshong** [comment]
@tannerzhang  - could you add the link to the counts you added to the CMS DQP? After you add your links and comments we can close this one.

**Comment by stephanieshong** [comment]
https://unite.nih.gov/workspace/slate/app/n3c-cms-pprl-linked-sites-dashboard

**Comment by stephanieshong** [comment]
CMS datasets are clipped to the PPRL Linked and CMS linkage opted-in sites. Therefore using the PPRL linkage person mapping table,  the final CMS datasets released to the data catalogue  are limited to the data that is associated with the N3C and CMS PPRL linked person IDs.
