### ISSUE TITLE
PCORnet pipeline updates to support CDM v6.1 changes

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#116]
With CDM v6.1, the following updates will need to be made in the pipeline: 
1. Support addition of ADDRESS_COUNTY field to LDS_ADDRESS_HISTORY table.
2. PRO_CM table contains survey data. This table will contain PHQ 2, 8 & 9 metrics amongst other SDoH like variables. Any new value set references for this table will need to be added to the  PCORnet mapping table.

**Comment by stephanieshong** [comment]
Some examples to consider as reference, notes copied from the PHQ_HungerVital-PRO_CM- guidance document
PRO_CM_ID PATID ENCOUNTERID PRO_DATE PRO_TIME
Example:
 PHQ-9 with score, but no item responses
0010 001 100001 01/25/2018
Example - PHQ-2 with item-level responses and score.  Item responses stored in EHR as text.
Please load all records related to the Patient Health Quesionnaire (PHQ) and Hunger Vital Sign (i.e., food security/insecurity) into the 
provided below.
Due to the way that the Hunger Vital Signs are structured and to simplify the process of loading records in general, we have modified some of the 
implementation guidance for the PRO_CM table and which fields to utilize.  Further details are listed below.
Load summary scores as stand-alone record.  It is not necessary to repeat the score across all related items.  This is a change from the current CDM 
guidance.  
The summary score for PHQ should be stored in PRO_MEASURE_SCORE (as indicated in the CDM specification).  The text-based summary for Hunger 
Vital should be stored in PRO_RESPONSE_TEXT (this guidance differs from the documentation in the CDM specification). Do not derive a summary value 
if it is not present in the source system.    
Assign the same value for PRO_MEASURE_SEQ to all responses that were captured as part of the same survey.  This includes all of the item responses and the 
summary score.  Each set of survey responses should have a unique value for PRO_MEASURE_SEQ.
The responses for the PHQ can be recorded as numeric or text.  Populate whichever is stored in your source system(s) (or both).  If only text is stored, do not derive 
the numeric value, or vice versa.  
Place the description of each item in PRO_ITEM_FULLNAME not PRO_ITEM_NAME.  Please place the description of each summary record in PRO_MEASURE_FULLNAME, 
not PRO_MEASURE_NAME
The preferred LOINC mappings for the PHQ and Hunger Vitals are provided in the "Preferred_LOINC_Mappings" tab.  There are several additional standardized 
questions that can be used to ascertain food security.  These questions may be present in the EHR, and LOINC mappings for these items can be found in the 
"Additional_LOINC_Mappings" tab.  There are also additional LOINC mappings for PHQ, though these pertain to CMS surveys of home health agencies and nursing 
home residents, and are not likely to be present with the EHR.  They are provided for completeness purposes in case records within the EHR have already been 
mapped to LOINC.
The value sets for each question are provided in the "Answer_ValueSets" tab. All of the PHQ items use the same value set.  The two main questions for the Hunger 
Vitals are provided in the ValueSets tab.  If you load additional questions from the Food Security Survey, please look up the appropriate values on the LOINC page. 
There are no LOINC codes for some of the questions in the PHQ-9 that has been modified for teens.  A LOINC code does exist for the summary score, so that can be 
loaded into PRO_CM according to these instructions.  If there are item-level responses for these surveys in your source system(s), please contact the DRN OC for 
assistance.
0011 002 20222 03/24/2022
0012 002 20222 03/24/2022
0013 002 20222 03/24/2022
Example - Hunger Vital with item-level responses and score.  Item responses store

**Comment by stephanieshong** [comment]
completed - will close after Lisa transfers the content over to the Jira.

**Comment by stephanieshong** [comment]
@Lisa Eskenazi - Please close this item when you are done copying the content over to the Jira. Thank you.

**Comment by lisa** [comment]
> @lisa Eskenazi - Please close this item when you are done copying the content over to the Jira. Thank you.

# `@lisa` User Notification

Hello! You're receiving this notice because you've tagged me, @lisa, on GitHub, likely in error. Lisa is a common first name, and happens to be mine. I use the @lisa username here on GitHub. While being tagged in various repositories is an interesting way for me to discover new projects (like this one!!), it's likely not your intention. Did you mean to tag someone else? Did you mean to use `@lisa` instead, in a [word as word](https://en.wikipedia.org/wiki/Use%E2%80%93mention_distinction) usage?

# Next Steps

I'm unsubscribing from this issue, pull request or project so if you meant to tag someone else to notify them, I would recommend that. If you meant to use my user ID as a plain string, without having GitHub notify me, you can do so by wrapping with backticks (the \` character), like so: `@lisa`.

**Comment by stephanieshong** [comment]
Oh, sorry about that. I will correct the tag.
Stephanie
