### ISSUE TITLE
CMS: Medicare and Medicaid - drug_expoure domain data should have overlapping data with EHR as well as additional data from CMS for PPRL linked person

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#122]
For  given PPRL linked person find out the overlapping and additional medication data coming in from the CMS data 
Medicare claim files with codes : 
IP = Inpatient ( We do not have NDCs from IP claims)..
OP = Outpatient
Part D Drug Event - NDCs are only present in the PartD drug events
HH = Home Health
HS = Hospice
DM = Durable Medical Equipment (e.g. Prosthetics, some drugs in NDC field is present )
PB = Part B = Carrier file
SN = Skilled Nursing 

Medicaid claim files with codes where the data may map to Drug_exposure: 
IP:
ICD10CM - ADMTG_DGNS_CD, DGNS_CD- multiple columns 
ICD10PCS - PRCDR_CD_1 - 6
LT:
ICD10CM - ADMTG_DGNS_CD
ICD10CM - DGNS_CD - multiple columns
OT:
ICD10CM - DGNS_CD - multiple columns
CPT or HCPCS - LINE_PRCDR_CD
RX:
NDC

**Comment by stephanieshong** [comment]
NDC codes are not provided in IP claims.

**Comment by stephanieshong** [comment]
We are going to check for the PPRL linked person in N3C and CMS how much drug data is overlapped and added in CMS. - Assigned to @gbeck

**Comment by stephanieshong** [comment]
@tannerzhang -I belive you added this the the CMS DQP.  Could you update this issue and close? Thank you.

**Comment by tannerzhang** [comment]
The comparison for the counts of PPRL linked cohort is reflected on the CMS Data Quality Portal (https://unite.nih.gov/workspace/slate/app/cms-data-quality-portal/home) and they do have overlaps, on average, for any linked patient, his Medicare version data has 19.4 more drugs (14.2 ingredients) compared to his N3C version, his Medicaid version has 16.8 more drugs (12.1 more ingredients) compared to the N3C version.
