### ISSUE TITLE
CMS: N3C PPRL linked person IDs have multiple CMS IDs. ( Medicaid and Medicare)  

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#123]
Out of the 306k N3C patients that have a match in CMS Medicare, 28k of them have have 2 CMS Ids each. 
Same should be checked in Medicaid.

**Comment by stephanieshong** [comment]
It is perfectly valid scenario to find multiple CMS ids associated with the N3C person. This can happen when the same person is found in both Medicare and Medicaid. This linkage is assigned to  @gbeck and @maya-choudhury for further investigation. They will look into this linkage where one N3C person is mapped to multiple CMS ids such that we do not double count claims data associated with the same N3C person.

**Comment by stephanieshong** [comment]
I am closing this for now, but it is valid to find via PPRL linkage same person in both Medicare and Medicaid. Since we have their PPRL linkage from Acumen, Palantir should be able to provide this map so that we can de-dup within CMS. @gianna-beck  
This is similar to what we did using the global_n3c_person_id in N3C. However this is just within CMS, i.e. Medicare and Medicaid.

**Comment by stephanieshong** [comment]
Let me know what you decide after talking with Saad.

**Comment by gbeck** [comment]
I don’t think I’m the intended recipient of this.

**Comment by stephanieshong** [comment]
Ah, sorry. Let me update the comment for @gianna-beck

**Comment by tannerzhang** [comment]
Hi @Stephanie Hong ***@***.***> ,

This was reported to the team before, but let me keep it here in case it is
relevant -- in the cms_mapping_table, some of the n3c ids were mapped to
two CMS Ids, which was aligned with the issue reported here. For the two
IDs matched to the same N3C ID, one was Medicare ID and the other was
Medicaid ID.  As of Nov 13, 2023, we do not have this issue anymore.

**Comment by stephanieshong** [comment]
@gianna-beck - reported that this has been address. This is due to Medicare person_id and Medicaid person_id mapping to same N3C person ID. There will be an additional mapping that which provides the map of Medicare person IDs and Medicaid person IDs that maps to same N3C person ID.
