### ISSUE TITLE
Request to add the MeSH term in the OMOP vocabulary tables used in N3C

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#125]
1. Add item id to the N3C vocabulary sync process- 
46 | MeSH | Medical Subject Headings (NLM) |   | 05-Nov-2023
2. Initiate a download process and ingest the updated version
3. Rebuild OMOP vocab. pipelines to sync MeSH terms and this terms are added into the concept table.
5. Do we need to update terminology mapping table to include the MeSH terms? - @bryanlaraway

**Comment by bryanlaraway** [comment]
Regarding the terminology mapping table update, I think this would be a good idea. However, it's unclear at this time whether or not any data partners are submitting MeSH concepts. It may be easiest to add MeSH to our included vocabularies and then run a query to see if anyone is including MeSH concepts. It doesn't look like any MeSH concepts are standard concepts, so we'll likely just need to focus on provided source concepts and look for those that aren't mapping to a standard concept at this time ('domain' _concept_id = 0).
