### ISSUE TITLE
Adopt or adapt method to capture & track mapping / heuristic choices for N3C Data Harmonization activities

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#20]
follow-up to 27May2020 "Large Group" discussion.  Harold Lehman asks if there are established methods / approaches to capturing and tacking mapping / implementation decisions or approaches, particularly in implementing OMOP.

Melissa Haendel suggests there is an ontology that addresses this purpose

**Comment by hlehmann17** [comment]
﻿(I need to turn this in to a GitHub issue)

H

**Comment by DaveraGabriel** [comment]
duplicate of #37
