### ISSUE TITLE
ACT data with modifier codes - potential data quality issue

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#24]
a quality issue may arise if ACT data contains modifiers to concepts which impact semantics.  Under current transformation models here is no place in the target for ACT modifier codes to go to.  If the semantics are impacted, this necessary info will me systematically lost

**Comment by DaveraGabriel** [comment]
ACT doesnt use the modifier code - if these are present: should be checked

**Comment by mim18** [comment]
ACT does not use the modifier_cd but sites may have them in their data. You should probably assess whether you try to harmonize that data at a later time. Example Pitt still uses its Med Dispense, Med Order, Med Fill modifiers even though they are not queriable via the ACT ontology.

**Comment by stephanieshong** [comment]
Since ACT does not use the modifier_cd we can close this issue.
