### ISSUE TITLE
Condition, Drug & Dose Era management in OMOP

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#27]
OMOP requires both beginning and end dates for condition dose and drug era tables.  Ingestion of data from CDMs which have one or both dates missing requires rules for managing missing end dates in a uniform way.  One suggestion is to add end dates the same as the start dates, creating eras of one day.  Of issue are those era tables that could be populated mixed with tables where the imputed end date creates eras of one day

**Comment by stephanieshong** [comment]
condition and drug era tables are built from the condition and drug_exposure domain with the beginning and end dates.

**Comment by stephanieshong** [comment]
We have determined that dose_era will not be built for now and currently it is not widely used in OMOP analytics.
