### ISSUE TITLE
Process for Lab code correction

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#36]
Should all recorded LOINC codes aligned w/ a standard source, if yes, then: should the sites be making these corrections or should this be performed as a part of the DI&H ingestion process?

**Comment by kmkostka** [comment]
From an OMOP stand point, we don't touch the source data. We take it as is and put it in the source concept ID and map that to the standard concept.

A site may determine they want to re-code their own source data at some point in time. We do not stop them from doing that.

**Comment by stephanieshong** [comment]
Within in D&IH process if the lab text is available and the LOINC CODE value is null, then we apply the logic to parse the lab text name and apply the logic to assign a LOINC code.

**Comment by stephanieshong** [comment]
Covid lab test name with the associated LOINC code is maintained in the pipeline. Should we encounter a COVID test with missing LOINC codes and we have the entry in the COVID test mapping table then we correct the null value with the COVID test LOINC code where the name matches in the mapping table.
