### ISSUE TITLE
PCORnet Sex Concept Mapping

### ISSUE THREAD

**Issue by tannerzhang** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#38]
Currently, we are not sure how source codes from PCORnet as 'NI', 'OT', and 'UN' should be mapped. Should they be mapped as '0's or the concept_ids given in Samvit mapping?

**Comment by kmkostka** [comment]
These are 0 - No Matching Concept.

**Comment by stephanieshong** [comment]
NI, OT and UN are getting mapped to 0
