### ISSUE TITLE
Need to agree on dataSetManifest structure

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#4]
What metadata do we want the sites to send along with the data. 
We suggest a data count table with row count for each domain/ table. 
We will need to incorporate the specifications for the site metadata table into the data extraction and submission part of the process. 
Some fields from Phenotype-Workstream should be included here. 
As the data moves along the different stage of ingestion and harmonization this manifest will follow and the dataset status field will be updated as the data moves from the SFTP site to secured N3C dataStore in the cloud.

**Comment by DaveraGabriel** [comment]
Closing this issue.  Version 1 of the data manifest [is documented here](https://github.com/National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization/wiki/DataSet-Contents-and-DataSetManifest-Structure)
