### ISSUE TITLE
N3C Data Pipeline Monitoring & Alerts 

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#41]
Per Amit V: (he wanted...) "To inform the stakeholders that there shall be "monitoring and alerts" capability for system and data events notification that are currently under development and scheduled to be rolled out for N3C use in the next 2-3 weeks"

IN the DI&H pipeline, what events will trigger alerts?
Who (which groups) will receive each kind of alert?
     Site Personnel
     N3C Admin 
     N3C Dashboard(s)
     N3C DI&H 
     N3C Analytics
     ...
What is the alert delivery mechanism?
     eMail
     Site directory "manifest" & related reports

**Comment by DaveraGabriel** [comment]
@LisaOKeefe1 is responsible for writing up site / client verbiage outlining the notification the sites will get re: their data in the ingestion process.  Am tagger her here to maintain the connection as we work through deploying these functions

**Comment by LisaOKeefe1** [comment]
> @LisaOKeefe1 is responsible for writing up site / client verbiage outlining the notification the sites will get re: their data in the ingestion process. Am tagger her here to maintain the connection as we work through deploying these functions

Not officially responsible. I've just had fellow PMs and others ask and want to be helpful to all if possible.

**Comment by wakibbe** [comment]
There is both the N3C operational view and the site notification piece, plus a general dashboard view of the milestone counts through the process. As we start doing this periodically (and as the period changes), showing the process of the latest data ingestion cycle, as well as each cycle. This will let us see potential issues as we change the overall process, QA steps, conformance.

**Comment by DaveraGabriel** [comment]
thanks @wakibbe ... a detail we should display on any dashboard status is the version of the payload.  Presumably site payloads will happen frequently.  We have established we will persist the latest 3 payloads on the sFTP server in the site-specific directory.  This could get tricky on a dashboard for you: providing status for up to 3 payloads.  A UI design nit for you to ponder...

**Comment by DaveraGabriel** [comment]
@wakibbe A component of the migration plan to a Production version for the DI&H pipeline includes notification triggers and schemas.  The most recent version of this plan / checklist is provided here
[N3C+Systems+-+monitoring+and+alerting+subscriptions (1).docx](https://github.com/National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization/files/4926459/N3C%2BSystems%2B-%2Bmonitoring%2Band%2Balerting%2Bsubscriptions.1.docx)

**Comment by hlehmann17** [comment]
(I wonder when it will be time for a new drawing of the workflow.)

H
