### ISSUE TITLE
Field length in DI&H target data base causing clipping / truncation

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#44]
Processing of a site data set reveals length of some fields shorter than the source data causing data loading to "clip" site data

**Comment by DaveraGabriel** [comment]
@stephanieshong this has been resolved through extending the length of the fields in Oracle to 255?  is this correct?

**Comment by stephanieshong** [comment]
Which issue number is this ?

**Comment by DaveraGabriel** [comment]
#44 ☺

Best,

Davera Gabriel, RN
Senior Research Terminologist

Johns Hopkins University
Institute for Clinical and Translational Research
2024 E Monument St, Suite I-200
Baltimore, MD 21287
+1 (530) 723-8356  davera@jhu.edu<mailto:davera@jhu.edu>

**Comment by stephanieshong** [comment]
Yes, this has been resolved.

**Comment by stephanieshong** [comment]
Yes, it is resolved.
