### ISSUE TITLE
Decoding Oracle Errors from Ingestion load

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#46]
A request from @empfff in 6/23 Office Hours session:  A human-readable list of the error log entries (or the most common ones) would be helpful to support the white glove support for Site data loads.  Particularly true for new sites / first time data load.  Currently Emily is using the error log Sandeep provided to support a site.  it would streamline to process to have a human-readable version or report to share w sites to remedy data errors from ingest process

**Comment by stephanieshong** [comment]
this is not handled via DQP and issues ticketing on the Enclave.
