### ISSUE TITLE
TriNetX Medication Frequency not required, and thus ignored

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#50]
OMOP does not require medication frequency.  initial mapping validation sessions decided to ignore this field.  If this field becomes needed in the future (ie:  when total doses are being calculated, or other need)  then "ignoring" will need to be replaced with mapping for this field

**Comment by hlehmann17** [comment]
In the Statistics group, a (strong) request was made for the ability to calculate pressor dosing, down to mcg/min. I responded that I was not sure we would have the data to support that calculation, but that I might be wrong.
