### ISSUE TITLE
Should the OMOP birth_year be defaulted if BD is absent in the source CDM?

### ISSUE THREAD

**Issue by cyaghmour** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#52]
If the source CDM does not provide a birth date, should the mandatory OMOP field PERSON.birth_year set to a default value? If so, what value?
Or, should that person, and his/her related clinical records, be ignored?

**Comment by kmkostka** [comment]
If you do not have a valid birth year, we should not include the person in our PERSON table. You need to have a valid birth year or you will get a Data Quality flag.

**Comment by stephanieshong** [comment]
We do have data partners submitting CDM demographics data with no birth year or month.  We process them and add to the unreleased LDS for data quality review.  DQP team will decide how to handle these cases per site case by case. (967, 819)
