### ISSUE TITLE
Rounding  / Stripping Dates to Midnight

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#56]
From: jhu-informatics-team@googlegroups.com <jhu-informatics-team@googlegroups.com> On Behalf Of Christopher Chute
Sent: Tuesday, June 30, 2020 1:08 PM
To: Pfaff, Emily <epfaff@email.unc.edu>; Bennett, Tell <TELL.BENNETT@CUANSCHUTZ.EDU>; Saltz, Joel <Joel.Saltz@stonybrookmedicine.edu>
Cc: jhu-informatics-team@googlegroups.com
Subject: RE: [N3C Tech Team] Important updates

Can we request that sites refrain from time stripping (to midnight).  Not sure where in the CMD pipeline this would be happening, but it if it is just before sending to N3C, there may be hope.

The harmonization team will need to explore how we do date and time shifting, that is +/- a fixed D:H:M in the 180 day window. 

Davera – please add to our issues list.

Chris

From: jhu-informatics-team@googlegroups.com <jhu-informatics-team@googlegroups.com> On Behalf Of Pfaff, Emily
Sent: Tuesday, June 30, 2020 12:52 PM
To: Christopher Chute <chute@jhu.edu>; Bennett, Tell <TELL.BENNETT@CUANSCHUTZ.EDU>; Saltz, Joel <Joel.Saltz@stonybrookmedicine.edu>
Cc: jhu-informatics-team@googlegroups.com
Subject: RE: [N3C Tech Team] Important updates

Luckily, the change that was mentioned in the tech notification email that Tell pasted below actually solved this problem before we even knew it was a problem.  Unless a site manually strips the timestamps, they will now be there. I believe we have updated the documentation to reflect that, but let me know if you see anything that still has the old “no timestamps” language.

Chris—note that this change will mean that Adeptia will have to adapt to consuming timestamps that are potentially formatted differently from each other. I assume it will be able to handle the heterogeneity (timestamps from site A have milliseconds, timestamps from site B do not), but thought I’d mention it.

One last bit of info—some sites may artificially set their timestamps to midnight in their source ETLs, effectively stripping them before they ever get to N3C. We may not have much power to change that. We may want to warn folks doing downstream analytics that timestamps of midnight should be viewed with suspicion. 

From: Christopher Chute <chute@jhu.edu> 
Sent: Tuesday, June 30, 2020 12:22 PM
To: Bennett, Tell <TELL.BENNETT@CUANSCHUTZ.EDU>; Saltz, Joel <Joel.Saltz@stonybrookmedicine.edu>
Cc: Pfaff, Emily <epfaff@email.unc.edu>; jhu-informatics-team@googlegroups.com
Subject: RE: [N3C Tech Team] Important updates

Agree.  Emily, I would keep time stamps, they are crucial to sequencing clinical events early in the care management odyssey (so to speak).  I profer this reference suggesting timestamps are consistent with safe harbor data:

PMID: 27013522
Preserving temporal relations in clinical data while maintaining privacy
George Hripcsak,corresponding author1 Parsa Mirhaji,2 Alexander FH Low,3 and Bradley A Malin4,5

Depending on the goal, one can choose a shift of integral days or continuous time, where the latter obscures both the date and the time-of-day. Under HIPAA Safe Harbor, time-of-day is not excluded. Because time-of-day can also be useful for research, especially in studies that are dependent on patient physiology, a shift with integral days can be helpful.

It was suggested during the clinical paper call that truncating to hour of day may be satisfactory, in a nod toward privacy.  Alternatively, we could explore date and time shifting, though this is trickier.  Meanwhile, do not let those times of day get lost please.

Chris

From: Bennett, Tell <TELL.BENNETT@CUANSCHUTZ.EDU> 
Sent: Tuesday, June 30, 2020 11:58 AM
To: Christopher Chute <chute@jhu.edu>; Saltz, Joel <Joel.Saltz@stonybrookmedicine.edu>
Cc: Pfaff, Emily <epfaff@email.unc.edu>
Subject: FW: [N3C Tech Team] Important updates

I didn’t realize this before. Huge impact on downstream usefulness of the data if timestamps can be included. Can we make a plea back to sites to start including them if they have them in their CDM?
Thanks very much,

-Tell

Change #4: Change to date format
 
Who’s affected? Everyone, but no action is required.
 
What’s the summary of the change?
•	Previously, we were very strict that all dates in extracts should have the timestamps lopped off. We are loosening this restriction due to our new understanding that the data ingestion process at the central hub will be able to remove the timestamps, rather than enforcing this at sites.
•	Thus, if you are suddenly seeing timestamps in your extracts, we wanted to let you know that there is no need to correct this. 
•	Documentation will be updated with this change tomorrow.
 
As always, we welcome your questions/comments/contributions on GitHub, Slack, and office hours. Thanks you for your partnership!
 
Best,
Emily
 
Emily Pfaff
Administrative Director, Informatics & Data Science
NC TraCS Institute

**Comment by DaveraGabriel** [comment]
From: jhu-informatics-team@googlegroups.com <jhu-informatics-team@googlegroups.com> On Behalf Of Pfaff, Emily
Sent: Tuesday, June 30, 2020 1:46 PM
To: Christopher Chute <chute@jhu.edu>; Bennett, Tell <TELL.BENNETT@CUANSCHUTZ.EDU>; Saltz, Joel <Joel.Saltz@stonybrookmedicine.edu>
Cc: jhu-informatics-team@googlegroups.com
Subject: RE: [N3C Tech Team] Important updates

We can’t control the timestamp stripping if they are doing so in their ETL from source. In our scripts, we will make sure that it is NOT happening between the site’s data and N3C—but if it’s happening between a site’s EHR and their CDM, that may not be within our jurisdiction.

I don’t think this will be the case with a huge number of sites. We may need to take it on a case-by-case basis, if you start seeing tons of midnight timestamps on ingest. Might be a good DQ check to add to the pile, if feasible.

**Comment by DaveraGabriel** [comment]
@richard1933 : I believe this is resolved?  please confirm :)

**Comment by richard1933** [comment]
@DaveraGabriel Yes, this is got solved. we're doing time shift with fuzz on top of date shift and apply to all dates persistent per person.
