### ISSUE TITLE
Site notification for data payload milestones

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#57]
The sites contributing data require notification when payloads achieve key milestones in the Data acquisition, ingestion and analytics pipelines.  Suggested (draft) milestones are: 1) successful upload to sFTP site, 2) in the DI&H pipelines, 3) return to sites for correction, 4) into merged data store and 5) available on analytics platform. 

The verbiage of notification, method of delivery and designated recipients are to be determined.

**Comment by DaveraGabriel** [comment]
related to N3C Data Pipeline Monitoring & Alerts #41

**Comment by DaveraGabriel** [comment]
![image](https://user-images.githubusercontent.com/48331201/86252438-373ad800-bb81-11ea-8183-bbe20481017c.png)

**Comment by mellybelly** [comment]
we should also have an indicator when a site is through the "In Merged Data Store" and has been pushed to "On Foundry" in the new site tracking sheet @jmcmurry

**Comment by wakibbe** [comment]
We need to be sure that we know which site is contributing the data so we can communicate back to it status of each milestones. We want to be sure we can provide both a dashboard of this process and notification back to the submitting site

**Comment by DaveraGabriel** [comment]
thank-you @wakibbe ... I just replied to you on #41 with a design "feature" that should be pondered:  how to display the status of more than one payload, as we are keeping the last 3 on the sFTP server

**Comment by stephanieshong** [comment]
released status is now reflected on the DQP page. Data issue are created and details are logged via the CDM SMEs an DI&H pipeline maintainers and helpers.
