### ISSUE TITLE
COVID-19 Lab Value Harmonization

### ISSUE THREAD

**Issue by mim18** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#59]
Perhaps harmonization of the Lab Values ( Detec, Pos, Neg, etc) is an opportunity for the NLP team to exercise their methods. We now have the raw Lab Values from at least 9 sites to test and validate against. Instead of asking each site to do it at this time see how close we can get using 'NLP' (maybe only regex is necessary?)

Also as ACT sites come on board we should be able to compare some site local mapping to values to NLP mappings as ACT sites are supposed to map to harmonized values of POSITIVE, NEGATIVE, PENDING and EQUIVOCAL

**Comment by linikujp** [comment]
One side question, are those sites using LOINC codes? 
FYI: There is a LOINC2HPO effort to link the positve, negative or other results to HPO terms.

**Comment by DaveraGabriel** [comment]
@linikujp : the HPO content is planned to be added to the tables in Palantir

@mim18 the alignment of qualitative lab results is underway in the DI&H pipeline, starting with the COVID tests.  DI&H team is adpating [TestNorm utility](https://academic.oup.com/jamia/article/doi/10.1093/jamia/ocaa145/5860833) to identify and re-label labs with null LOINC coding & differing names.  Additionally,  More specific than but somewhat related to: Process for Lab code correction #36 issue as well

**Comment by DaveraGabriel** [comment]
tagging @jiaola for reference

**Comment by DaveraGabriel** [comment]
@mim18: when we start processing the ACT pipeline, we will revisit this issue with you to ensure the established process created for PCORnet meets the spirit of the issue you have logged here

**Comment by pambanning** [comment]
With kit/reagent diminished supplies there are now guidelines from Dept of Health and Human Services on performing testing on pools of patients; the results should be worded differently from detected/not detected. SNOMED CT has created new terms accordingly for test values. [https://www.hhs.gov/sites/default/files/hhs-guidance-implementation.pdf](url)

**Comment by stephanieshong** [comment]
We have created a mapping file to correct the missing LOINC code with LOINC for COVID tests. 
The mapping file will get continually updated as the new tests are developed and LOINC code gets updated.

https://github.com/National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization/wiki/COVID19-LOINC-code--corrected
