### ISSUE TITLE
Palantir Data Characterization High Level Pipeline for each LDS

### ISSUE THREAD

**Issue by hlehmann17** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#63]
Action | Code
-------|-------
Apply DQ Checks | The DI&H Repository
Apply Transformations |  Formulas, Aggregations
<Inform site vs DI&H group> |  
Join into LDS DataStore [Includes updating the DataStore version number] |  
Regenerate Safe Harbor DataStore [Includes updating the SH version number] |  
Inform downstream clients of the update| build tag - release version|

**Comment by stephanieshong** [comment]
-  dqd_instance.R is run and the <siteAbbrevName>.json is generated and stored in the outgoing folder. 

- data build version is generated and stored in the LDS data store in the manifest_abridged table for each update. 

- SafeHarbor dataSet is generated within N3C enclave.

- Release data Set is flagged as released=TRUE for safe Harbor build.
