### ISSUE TITLE
Incorrect ValueSet Mapping for AV visit types for PCORnet CDM 

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#65]
581478 | Encounter Type-AV | Ambulatory visit | Encounter Type | Non-standard | Valid | Observation | PCORNet
-- | -- | -- | -- | -- | -- | -- | --

**Comment by stephanieshong** [comment]
This is a mis-mapped value, the correct value for this encounter type should be 44814708.

44814708 | Encounter Type-AV | Ambulatory visit | Encounter Type | Non-standard | Valid | Observation | PCORNet
-- | -- | -- | -- | -- | -- | -- | --

**Comment by stephanieshong** [comment]
@cyaghmour @kmkostka @DaveraGabriel 
Could you check if correct value should be  44814708 and not 581478?  The mapping document is set to 581478.

**Comment by stephanieshong** [comment]
We will use 9202 if AV is used for enc_type which is outpatient visit.

**Comment by kmkostka** [comment]
> @cyaghmour @kmkostka @DaveraGabriel
> Could you check if correct value should be 44814708 and not 581478? The mapping document is set to 581478.

Yes, you’re right. This is why it’s good to have two reviewers.

**Comment by stephanieshong** [comment]
Addressed.
