### ISSUE TITLE
Establish minimum required data per CDM for successful upload / initiation of payloads into DI&H pipeline

### ISSUE THREAD

**Issue by DaveraGabriel** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#66]
A set of criteria for successful ingestion into the DI&H pipeline and not sent back to sites for correction needed to be established.  A component of these criteria is declaring the minimum required data per CDM for a successful upload.  @empfff  created a [Google worksheet for this purpose](https://docs.google.com/spreadsheets/d/11vG24P7_hVFDsG2BrPCmRNaL1y6HKFCL-B51f9CIf8w/edit#gid=0).

**Comment by DaveraGabriel** [comment]
@mim18 the google sheet linked above has a tab for ACT.  is there specific content missing?

**Comment by stephanieshong** [comment]
the cdm required minimun table list is updated in the following wiki page:
https://github.com/National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization/wiki/Required-table-by-CDM
