### ISSUE TITLE
We are missing SARS-Cov-2 Test Results for Sites 6000

### ISSUE THREAD

**Issue by agirvin** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#67]
We are currently missing SARS-CoV-2 Test results for sites 7000 (known) and 6000 (possibly not known).

This the breakdown of test type by site:

![image](https://user-images.githubusercontent.com/68359621/87615749-686aea80-c6e1-11ea-8f5d-d2b41970e7b2.png)

And these are the result values:

![image](https://user-images.githubusercontent.com/68359621/87615783-7a4c8d80-c6e1-11ea-8b24-31674d2fc254.png)

As was known, thee site 7000 values aren't mapped.  But in the case of site 6000, we actually see the concept_id for the test itself in both the measurement_concept_id _and_ value_as_concept_id column 

![image](https://user-images.githubusercontent.com/68359621/87616070-3908ad80-c6e2-11ea-83ba-35013f0ec405.png)

That is, the measurement_concept_name is "SARS coronavirus 2 N gene [Presence] in Unspecified specimen by NAA with probe detection" and the value_as_concept_name is "SARS coronavirus 2 N gene [Presence] in Unspecified specimen by NAA with probe detection"

The analysis is [here](https://unite.nih.gov/workspace/contour-app/ri.contour.main.analysis.cc074674-69e4-4c37-a78e-ac53a1d9fd94/path/ri.contour.main.ref.c023f68e-6e49-4bd0-913d-03e1a56bc4fb/board/fa6560f1-c6c0-397c-9b0b-c32362ff4791?viewMode=edit)

**Comment by DaveraGabriel** [comment]
@agirvin  : the datastore you worked with was not ready / intended for your analyses yesterday.  We are addressing the "publish to Palanitr" steps / workflow, including a regular cadence (twice weekly) for enclave data refresh to avoid this in the future.  However, we are also looking into the information you have provided today. @rajuhemadri

**Comment by stephanieshong** [comment]
Corrected for site 7000, the qualitative results are set as value as concept id. As for site 6000, the new dataSet will be requested with the corrected value as concept id.
